export const FOOTER_LINKS = [
  { path: '/123', name: 'Meta' },
  { path: '/', name: 'Giới thiệu' },
  { path: '/accounts/signup', name: 'Blog' },
  { path: '/accounts/login', name: 'Việc làm' },
  { path: '/123/posts', name: 'Trợ giúp' },
  { path: '/', name: 'API' },
  { path: '/', name: 'Quyền riêng tư' },
  { path: '/', name: 'Điều khoản' },
  { path: '/', name: 'Tài khoản liên quan nhất' },
  { path: '/', name: 'Vị trí' },
  { path: '/', name: 'Instagram Lite' },
  { path: '/', name: 'Tải thông tin người liên hệ lên & người không phải người dùng' },
  { path: '/', name: 'Meta đã xác minh' }
]

export const LANGUEGES = [
  { value: 'af', name: 'Afrikaans' },
  { value: 'cs', name: 'Čeština' },
  { value: 'da', name: 'Dansk' },
  { value: 'de', name: 'Deutsch' },
  { value: 'el', name: 'Ελληνικά' },
  { value: 'en', name: 'English' },
  { value: 'en-gb', name: 'English (UK)' },
  { value: 'es', name: 'Español (España)' },
  { value: 'es-la', name: 'Español' },
  { value: 'fi', name: 'Suomi' },
  { value: 'fr', name: 'Français' },
  { value: 'id', name: 'Bahasa Indonesia' },
  { value: 'it', name: 'Italiano' },
  { value: 'ja', name: '日本語' },
  { value: 'ko', name: '한국어' },
  { value: 'ms', name: 'Bahasa Melayu' },
  { value: 'nb', name: 'Norsk' },
  { value: 'nl', name: 'Nederlands' },
  { value: 'pl', name: 'Polski' },
  { value: 'pt-br', name: 'Português (Brasil)' },
  { value: 'pt', name: 'Português (Portugal)' },
  { value: 'ru', name: 'Русский' },
  { value: 'sv', name: 'Svenska' },
  { value: 'th', name: 'ภาษาไทย' },
  { value: 'tl', name: 'Filipino' },
  { value: 'tr', name: 'Türkçe' },
  { value: 'zh-cn', name: '中文(简体)' },
  { value: 'zh-tw', name: '中文(台灣)' },
  { value: 'bn', name: 'বাংলা' },
  { value: 'gu', name: 'ગુજરાતી' },
  { value: 'hi', name: 'हिन्दी' },
  { value: 'hr', name: 'Hrvatski' },
  { value: 'hu', name: 'Magyar' },
  { value: 'kn', name: 'ಕನ್ನಡ' },
  { value: 'ml', name: 'മലയാളം' },
  { value: 'mr', name: 'मराठी' },
  { value: 'ne', name: 'नेपाली' },
  { value: 'pa', name: 'ਪੰਜਾਬੀ' },
  { value: 'si', name: 'සිංහල' },
  { value: 'sk', name: 'Slovenčina' },
  { value: 'ta', name: 'தமிழ்' },
  { value: 'te', name: 'తెలుగు' },
  { value: 'vi', name: 'Tiếng Việt' },
  { value: 'zh-hk', name: '中文(香港)' },
  { value: 'bg', name: 'Български' },
  { value: 'fr-ca', name: 'Français (Canada)' },
  { value: 'ro', name: 'Română' },
  { value: 'sr', name: 'Српски' },
  { value: 'uk', name: 'Українська' }
]
